services:
  bookify.webapi:
    image: ${DOCKER_REGISTRY-}bookifywebapi
    container_name: Bookify.WebApi
    build:
      context: .
      dockerfile: Bookify.WebApi/Dockerfile
    depends_on:
      - bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

volumes:
  pgdata:
